{{- if .Values.apikey.generateRandomApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "baget.fullname" . }}-apikey-secret
  labels:
{{ include "baget.labels" . | indent 4 }}
type: Opaque
data:
  apikey: {{ randAlphaNum 24 | b64enc | quote }}
{{- end }}
