{{- if .Values.persistence.pdName -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pdName }}
  labels:
{{ include "baget.labels" . | indent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.storageSize }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ template "baget.fullname" . }}-data
  gcePersistentDisk:
    pdName: {{ .Values.persistence.pdName }}
    fsType: {{ .Values.persistence.fsType }}
{{- end }}
